language: node_js
sudo: false
node_js:
  - '0.10'
  - '0.11'
  - '0.12'
  - iojs

cache:
  directories:
    - node_modules
    - bower_components

matrix:
  fast_finish: true
  allow_failures:
    - node_js: iojs

before_script:
  - npm install -g bower grunt-cli
  - gem install sass
  - bower install
services: mongodb
